# Generated by Django 4.2.19 on 2025-04-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firegame', '0002_map_delete_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='firegame_Map',
        ),
    ]
