# Generated by Django 4.2.19 on 2025-04-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firegame', '0003_rename_map_firegame_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='firegame_map',
            name='bot_index',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firegame_map',
            name='ext_index',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firegame_map',
            name='fire_index',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
