# Generated by Django 4.2.19 on 2025-04-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firegame', '0004_firegame_map_bot_index_firegame_map_ext_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firegame_map',
            name='bot1path',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firegame_map',
            name='bot2path',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firegame_map',
            name='bot3path',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firegame_map',
            name='bot4path',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
