# Generated by Django 4.2.19 on 2025-04-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firegame', '0005_firegame_map_bot1path_firegame_map_bot2path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firegame_map',
            name='successpossiblepath',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
