# Generated by Django 4.2.19 on 2025-04-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firegame', '0006_firegame_map_successpossiblepath'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='firegame_Map',
            new_name='FiregameMap',
        ),
    ]
