# Generated by Django 4.2.19 on 2025-04-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firegame', '0007_rename_firegame_map_firegamemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firegamemap',
            name='bot2path',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='firegamemap',
            name='bot3path',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='firegamemap',
            name='bot4path',
            field=models.JSONField(null=True),
        ),
    ]
