# Generated by Django 4.2.19 on 2025-06-11 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mousegame', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firegame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MousegameGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_path', models.JSONField()),
                ('sensor_log', models.JSONField()),
                ('result', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('mousegame_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mousegame.mousegamemap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FiregameGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_path', models.JSONField()),
                ('result', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('firegame_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firegame.firegamemap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='mousegamegame',
            constraint=models.UniqueConstraint(fields=('mousegame_map', 'user'), name='unique_mousegame_map_user'),
        ),
        migrations.AddConstraint(
            model_name='firegamegame',
            constraint=models.UniqueConstraint(fields=('firegame_map', 'user'), name='unique_firegame_map_user'),
        ),
    ]
