# Generated by Django 4.2.19 on 2025-04-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MousegameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField()),
                ('stochastic', models.BooleanField()),
                ('bot_starting_index', models.JSONField()),
                ('mouse_starting_index', models.JSONField()),
                ('mouse_path', models.JSONField()),
                ('num_turns', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.JSONField()),
                ('states', models.JSONField()),
                ('bot', models.SmallIntegerField()),
                ('mousegame_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mousegame.mousegamemap')),
            ],
        ),
    ]
