# Generated by Django 4.2.19 on 2025-04-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mousegame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mousegamemap',
            old_name='board',
            new_name='grid',
        ),
    ]
