# Generated by Django 4.2.19 on 2025-05-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mousegame', '0002_rename_board_mousegamemap_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mousegamemap',
            name='sensor_sensitivity',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
