# Generated by Django 4.2.19 on 2025-05-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mousegame', '0003_mousegamemap_sensor_sensitivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdata',
            name='modechange',
            field=models.IntegerField(null=True),
        ),
    ]
