# Generated by Django 4.2.19 on 2025-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mousegame', '0004_botdata_modechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdata',
            name='plans',
            field=models.JSONField(null=True),
        ),
    ]
