# Generated by Django 4.2.19 on 2025-06-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mousegame', '0005_botdata_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botdata',
            name='states',
            field=models.JSONField(null=True),
        ),
    ]
