# Generated by Django 4.2.19 on 2025-06-11 16:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MousegameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.JSONField()),
                ('stochastic', models.BooleanField()),
                ('bot_starting_index', models.JSONField()),
                ('mouse_starting_index', models.JSONField()),
                ('mouse_path', models.JSONField()),
                ('num_turns', models.IntegerField()),
                ('sensor_sensitivity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans', models.JSONField(null=True)),
                ('evidence', models.JSONField()),
                ('states', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None), size=None), null=True, size=None)),
                ('modechange', models.IntegerField(null=True)),
                ('bot', models.SmallIntegerField()),
                ('mousegame_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mousegame.mousegamemap')),
            ],
        ),
    ]
