# Generated by Django 4.2.19 on 2025-04-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board_state',
            field=models.JSONField(),
        ),
    ]
