# Generated by Django 4.2.19 on 2025-04-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_game_board_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board_state',
            field=models.TextField(),
        ),
    ]
