# Generated by Django 4.2.19 on 2025-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiregameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_board', models.JSONField()),
                ('fire_progression', models.JSONField()),
                ('bot_index', models.JSONField()),
                ('fire_index', models.JSONField()),
                ('ext_index', models.JSONField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('successpossiblepath', models.JSONField()),
                ('bot1path', models.JSONField()),
                ('bot2path', models.JSONField(null=True)),
                ('bot3path', models.JSONField(null=True)),
                ('bot4path', models.JSONField(null=True)),
            ],
        ),
    ]
