# Generated by Django 4.2.19 on 2025-05-12 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mousegame', '0005_botdata_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='MousegameGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_path', models.JSONField()),
                ('win', models.BooleanField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('mousegame_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mousegame.mousegamemap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
