# Generated by Django 4.2.19 on 2025-05-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mousegamegame',
            name='win',
            field=models.CharField(max_length=10),
        ),
    ]
