# Generated by Django 4.2.19 on 2025-05-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_win_mousegamegame_result'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mousegamegame',
            constraint=models.UniqueConstraint(fields=('mousegame_map', 'user'), name='unique_mousegame_map_user'),
        ),
    ]
