# Generated by Django 4.2.19 on 2025-05-21 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firegame', '0008_alter_firegamemap_bot2path_and_more'),
        ('api', '0004_mousegamegame_unique_mousegame_map_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiregameGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_path', models.JSONField()),
                ('result', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('firegame_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firegame.firegamemap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
