# Generated by Django 4.2.19 on 2025-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_firegamegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='mousegamegame',
            name='sensor_log',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
