# Generated by Django 4.2.19 on 2025-06-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mousegamegame_sensor_log'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='firegamegame',
            constraint=models.UniqueConstraint(fields=('firegame_map', 'user'), name='unique_firegame_map_user'),
        ),
    ]
